DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE PEDIDO_H CASCADE CONSTRAINTS;
DROP TABLE PEDIDO_B CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE ORDEN_H CASCADE CONSTRAINTS;
DROP TABLE ORDEN_B CASCADE CONSTRAINTS;
DROP TABLE PLATILLO CASCADE CONSTRAINTS;
DROP TABLE MESA CASCADE CONSTRAINTS;
DROP TABLE RESERVA CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE DOCUMENTO CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTE CASCADE CONSTRAINTS;


CREATE TABLE USUARIO
(
    RUT                 NUMBER PRIMARY KEY,
    DV                  CHAR NOT NULL,
    USERNAME            VARCHAR(70) NOT NULL,
    PASSWORD            VARCHAR(255) NOT NULL,
    NOMBRE              VARCHAR(70) NOT NULL,
    APELLIDO            VARCHAR(70) NOT NULL,
    ROL                 NUMBER NOT NULL,
    CORREO              VARCHAR(255) NOT NULL,
    FECHA_NACIMIENTO    DATE NOT NULL
);

CREATE TABLE PROVEEDOR 
(
    RUT         		VARCHAR(15) PRIMARY KEY,
    NOMBRE      		VARCHAR(70) NOT NULL,
    TELEFONO    		VARCHAR(15) NOT NULL,
    DIRECCION   		VARCHAR(255) NOT NULL,
    CORREO      		VARCHAR(255) NOT NULL  
);

CREATE TABLE PEDIDO_H 
(
    ID              	NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    TOTAL           	NUMERIC NOT NULL,
    ESTADO	    		NUMERIC NOT NULL,
    PROVEEDOR_ID    	VARCHAR(15) NOT NULL,
    DOCUMENTO_ID    	NUMERIC NOT NULL
);

CREATE TABLE PEDIDO_B
(
    ID              	NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CANTIDAD        	NUMERIC NOT NULL,
    SUBTOTAL        	NUMERIC NOT NULL,
    PEDIDO_H_ID     	NUMERIC NOT NULL,
    PRODUCTO_ID     	NUMERIC NOT NULL
);

CREATE TABLE PRODUCTO 
(
    ID              	NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NOMBRE          	VARCHAR(70) NOT NULL,
    DESCRIPCION     	VARCHAR(255) NOT NULL,
    CANTIDAD        	NUMERIC NOT NULL,
    PRECIO          	NUMERIC NOT NULL,
    CATEGORIA       	VARCHAR(70) NOT NULL
);

CREATE TABLE DOCUMENTO 
(
    ID      			NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    FECHA   			DATE NOT NULL,
    HORA    			VARCHAR(5),
    TIPO    			NUMERIC
);

CREATE TABLE ORDEN_H
(
    ID              	NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    TOTAL           	NUMERIC NOT NULL,
    ESTADO          	NUMERIC NOT NULL,
    DOCUMENTO_ID    	NUMERIC NOT NULL,
    MESA_ID         	NUMERIC NOT NULL
);

CREATE TABLE ORDEN_B
(
    ID              	NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CANTIDAD        	NUMERIC NOT NULL,
    SUBTOTAL        	NUMERIC NOT NULL,
    ORDEN_H_ID      	NUMERIC NOT NULL,
    PLATILLO_ID     	NUMERIC NOT NULL
);

CREATE TABLE MESA
(
    ID          		NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NUMERO      		NUMERIC NOT NULL,
    CAPACIDAD   		NUMERIC NOT NULL,
	ESTADO				NUMERIC NOT NULL
);

CREATE TABLE CLIENTE
(
    RUT         		NUMERIC PRIMARY KEY,
    DV          		CHAR NOT NULL,
    NOMBRE      		VARCHAR(70) NOT NULL,
    APELLIDO    		VARCHAR(70) NOT NULL,
    CORREO      		VARCHAR(255) NOT NULL,
    TELEFONO    		VARCHAR(255) NOT NULL  
);

CREATE TABLE RESERVA
(
    ID                  NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    FECHA               DATE NOT NULL,
    HORA                VARCHAR(5) NOT NULL,
    CANTIDAD_PERSONAS   NUMERIC NOT NULL,
	ESTADO				NUMERIC NOT NULL,
    CLIENTE_ID          NUMERIC NOT NULL,
    MESA_ID             NUMERIC NOT NULL
);

CREATE TABLE PLATILLO
(
    ID          		NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NOMBRE      		VARCHAR(70) NOT NULL,
    TIEMPO      		NUMERIC NOT NULL,
	PRECIO				NUMERIC NULL
);

CREATE TABLE INGREDIENTE
(
    ID              	NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CANTIDAD        	NUMERIC NOT NULL,
    PLATILLO_ID     	NUMERIC NOT NULL,
    PRODUCTO_ID     	NUMERIC NOT NULL
);

ALTER TABLE PEDIDO_H ADD CONSTRAINT fk_PEDIDO_H_DOCUMENTO FOREIGN KEY (DOCUMENTO_ID) 
REFERENCES DOCUMENTO(ID);

ALTER TABLE PEDIDO_H ADD CONSTRAINT fk_PEDIDO_H_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID) 
REFERENCES PROVEEDOR(RUT);

ALTER TABLE PEDIDO_B ADD CONSTRAINT fk_PEDIDO_B_PEDIDO_H FOREIGN KEY (PEDIDO_H_ID) 
REFERENCES PEDIDO_H(ID);

ALTER TABLE PEDIDO_B ADD CONSTRAINT fk_PEDIDO_H_PRODUCTO FOREIGN KEY (PRODUCTO_ID) 
REFERENCES PRODUCTO(ID);

ALTER TABLE ORDEN_H ADD CONSTRAINT fk_ORDEN_H_DOCUMENTO FOREIGN KEY (DOCUMENTO_ID) 
REFERENCES DOCUMENTO(ID);

ALTER TABLE ORDEN_H ADD CONSTRAINT fk_ORDEN_H_MESA FOREIGN KEY (MESA_ID) 
REFERENCES MESA(ID);

ALTER TABLE ORDEN_B ADD CONSTRAINT fk_ORDEN_B_ORDEN_H FOREIGN KEY (ORDEN_H_ID) 
REFERENCES ORDEN_H(ID);

ALTER TABLE ORDEN_B ADD CONSTRAINT fk_ORDEN_B_PLATILLO FOREIGN KEY (PLATILLO_ID) 
REFERENCES PLATILLO(ID);

ALTER TABLE RESERVA ADD CONSTRAINT fk_RESERVA_MESA FOREIGN KEY (MESA_ID) 
REFERENCES MESA(ID);

ALTER TABLE RESERVA ADD CONSTRAINT fk_RESERVA_CLIENTE FOREIGN KEY (CLIENTE_ID) 
REFERENCES CLIENTE(RUT);

ALTER TABLE INGREDIENTE ADD CONSTRAINT fk_INGREDIENTE_PLATILLO FOREIGN KEY (PLATILLO_ID) 
REFERENCES PLATILLO(ID);

ALTER TABLE INGREDIENTE ADD CONSTRAINT fk_INGREDIENTE_PRODUCTO FOREIGN KEY (PRODUCTO_ID) 
REFERENCES PRODUCTO(ID);


COMMIT;

